### ISSUE TITLE
Problem Injecting SSH Keys(Windows 10)

### ISSUE THREAD

**Issue by Gonzalo2683** [drupal-graphql/drupal-decoupled-app#388]
Hello, 

I have generated the keys but at the moment of run the command:  `ssh-key-add.cmd C:\Users\[yourname]\.ssh\id_rsa`  , i get the following message:

```
Unable to find image 'amazeeio/ssh-agent:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/amazeeio/ssh-agent/manifests/latest: unauthorized: incorrect username or password.
See 'docker run --help'.
```

What could be the problem?

Thanks

**Comment by fubhy** [comment]
Please check with the amazee.io team for support for this.
