### ISSUE TITLE
@amazee/react-scripts – npm

### ISSUE THREAD

**Issue by signalwerk** [drupal-graphql/drupal-decoupled-app#398]
I found a bug in the package `@amazee/react-scripts` this repo is using. Unfortunately the github-project (https://github.com/AmazeeLabs/amazee-js) is not longer available. Any suggestions how to file the bug now? Would be great if @Schnitzel or @fubhy could bring it back. 🙊

**Comment by fubhy** [comment]
It was never public AFAIK. It's a custom fork we made from CRA. I am going to move this project towards next.js in the next days anyways so it will not be using it for much longer anyways. Stay tuned!

**Comment by fubhy** [comment]
@signalwerk I've started to work on it here: https://github.com/drupal-graphql/drupal-decoupled-app/pull/399

Just a few final tweaks left. Works already.

**Comment by signalwerk** [comment]
😻 wow. massive pr. I'm right now on a productive project with the current setup. I think we try to switch with our codebase as well, since we are not nearly finished now. and with next in place we can configure the webpack like we need it. that sounds good! thx a lot for your work!

**Comment by fubhy** [comment]
@signalwerk I've merged the pull request. There are a few things missing I'd like to add later: https://github.com/drupal-graphql/drupal-decoupled-app/issues/400

**Comment by signalwerk** [comment]
@fubhy thanks a lot! looks like there is still a way to go! unfortunately we (the company attribute from zurich & me as a freelancer) are quite new in the game with decoupled-drupal and we are not sure if we are really a help at that stage. But we try whenever possible to bring stuff upstream. 
do you think at the current state it makes sense to switch to the next.js setup? or do you think we should role with the old one?
