### ISSUE TITLE
static files (svg, woff, ...)

### ISSUE THREAD

**Issue by signalwerk** [drupal-graphql/drupal-decoupled-app#406]
If I see it correct there is in the `frontend/server/index.ts` no handling for static files. Something like `  server.use("/_next/static", express.static(path.join(__dirname, '../static')));` could be usefull.

**Comment by fubhy** [comment]
That's already in there if you import your file assets. Next then handles theses files automatically.

**Comment by fubhy** [comment]
Actually no, you are right. I did not add the import file handling yet. One sec ...

**Comment by fubhy** [comment]
@signalwerk Added it, together with an example.

**Comment by signalwerk** [comment]
@fubhy looking good! I had the case that I used woff's in a css file. do I have to wabpack that somehow? 🤔 that could also be the case for icon's and stuff when I have them in a css (to use @media). or maybe it's only my use-case and not a general thin that should end up in that boilerplate... it works actually with the static route I added in my case.

**Comment by fubhy** [comment]
You can either register your own static route or add webpack processing for CSS files according to your needs. It would then also transpile the files imported in .css files.

**Comment by signalwerk** [comment]
@fubhy ok. thx. I roll with the static route for the moment. thx.

**Comment by fubhy** [comment]
@signalwerk By the way, we got a #graphql Slack channel on the Drupal slack.

**Comment by signalwerk** [comment]
@fubhy 😳 all right – cool. I'm in.
