### ISSUE TITLE
ERROR: Service "cli" mounts volumes from "amazeeio-ssh-agent", which is not the name of a service or container.

### ISSUE THREAD

**Issue by readingdan** [drupal-graphql/drupal-decoupled-app#410]
docker-compose build
ERROR: Service "cli" mounts volumes from "amazeeio-ssh-agent", which is not the name of a service or container.

**Comment by fubhy** [comment]
You have to install amazee.io as mentioned in the README if you want to use the pre-configured Docker setup. See the docs here: https://docs.amazee.io/
