### ISSUE TITLE
Docker build error 

### ISSUE THREAD

**Issue by gcosgreave-us** [drupal-graphql/drupal-decoupled-app#413]
When running "docker-build" out the box I get the following error: 

ERROR: Service "cli" mounts volumes from "amazeeio-ssh-agent", which is not the name of a service or container.

**Comment by gcosgreave-us** [comment]
Sorry this does seem to be an issue unless I am missing something. I have started the build however by changing the container name that mounts to amazeeio-dnsmasq

**Comment by fubhy** [comment]
Yep, as stated in the docs, this demo app is built around amazeeio. That means you have to run it with the amazeeio toolchain locally (that's also stated in the project readme). Please refer to docs.amazee.io for that. If you continue to have the aforementioned issue, please come back here :).

PS: If you want, you can of course also run it without amazeeio but then you have to set up and orchestrate the docker containers yourself.

**Comment by fubhy** [comment]
There is also an open issue to add support for Lando #404. But I haven't found time to work on that yet.

**Comment by swr82** [comment]
@gcosgreave-us 

Try 
`gem install pygmy` or `sudo gem install pygmy` and then,
`pygmy up` in terminal before running `docker-compose build` to setup amazeeio...

**Comment by scotthorn** [comment]
I was missing the `pygmy up`, which isn't mentioned in the other docs I've need. Thanks @swr82 !
