### ISSUE TITLE
Server side rendering Question

### ISSUE THREAD

**Issue by AlexJenter** [drupal-graphql/drupal-decoupled-app#414]
Not sure if I'm doing it right but i am under the impression that the only page in this example that is being delivered by the server is `/home`. At least out of the box, overview, articles and pages are missing in the initial source file after running through the steps provided in the readme.

**Comment by fubhy** [comment]
The routes are registered here (we don't use the default mechanism from next.js that automatically picks up all files in the pages directory): https://github.com/drupal-graphql/drupal-decoupled-app/blob/master/frontend/server/routes.ts

**Comment by AlexJenter** [comment]
Thanks for pointing that out, as we only figured that out and weren't sure if we are doing it right. But the issue kind of remains if we want pages with content from graphql to be rendered by the server. E.g. if i use this Repo as is and cUrl th3e route `/node` the body only contains the two empty divs with ids `__next` and `__next-error`. If we want SSR with data from Graphql would we have to do something as described here on [apollographql.com](https://www.apollographql.com/docs/react/features/server-side-rendering.html)?
